### ISSUE TITLE
Is this being actively maintained?

### ISSUE THREAD

**Issue by michael-hart-github** [jhagrid77/CDDA-Ubuntu-Launcher#14]
Hello,
I would be interested in using a Linux-friend CDDA launcher. It appears some early work has been done here but hasn't been updated in some time. Can anyone please confirm if this is still actively being maintained?

**Comment by jhagrid77** [comment]
There was a bit of work done in the "test" branch (great name I know), though this was all prior to lots of changing taking place with CDDA (such as the drop for Lua support).

At this time, CDDA-Linux-Launcher is not being actively maintained. I unfortunately have not been able to find the time since I have began working.

It also seems like none of the current forks have been worked on either.

**Comment by michael-hart-github** [comment]
Sorry to hear that. Thank you for the response, @jhagrid77.
